# Generated by Django 2.1.3 on 2018-11-09 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Room occupied at:')),
                ('date_end', models.DateField(verbose_name='Room freed at:')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('occupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='detection.Room'),
        ),
    ]
