# Generated by Django 2.1.3 on 2018-11-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_auto_20181109_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='room',
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
