# Generated by Django 2.1.3 on 2018-11-10 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_auto_20181109_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='room_record',
            field=models.ForeignKey(default=102, on_delete=django.db.models.deletion.CASCADE, to='detection.Room'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='date_end',
            field=models.DateTimeField(verbose_name='Room freed at:'),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_start',
            field=models.DateTimeField(verbose_name='Room occupied at:'),
        ),
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
